export const trending = [
  {
    id: 1,
    price: "0.005 sUSD",
    free: false,
    duration: "18:24",
    title: "Learn Solidity Smart Contracts from Scratch — Complete Tutorial",
    author: "@user",
    initials: "BD",
    views: "0 views",
    color: "#071b12",
  },
  {
    id: 2,
    price: "Free",
    free: true,
    duration: "42:10",
    title: "On-Chain Data Analysis with Solana — Latest In-Depth Workshop",
    author: "@user",
    initials: "SA",
    views: "0 views",
    color: "#f3e6d4",
  },
  {
    id: 3,
    price: "0.10 sUSD",
    free: false,
    duration: "1:02:33",
    title: "Building Web3 Applications with Modern Frameworks — Practical Guide",
    author: "@user",
    initials: "MV",
    views: "0 views",
    color: "#dde2f3",
  },
];

export const free = [
  {
    id: 4,
    price: "Free",
    free: true,
    duration: "12:05",
    title: "Crypto Wallet Basics and How to Secure Your Account",
    author: "@user",
    initials: "DV",
    views: "0 views",
    color: "#dcefe0",
  },
  {
    id: 5,
    price: "Free",
    free: true,
    duration: "8:47",
    title: "Artistic NFT Trends and How to Create Your First Collection",
    author: "@user",
    initials: "NA",
    views: "0 views",
    color: "#f1e2f0",
  },
  {
    id: 6,
    price: "Free",
    free: true,
    duration: "25:18",
    title: "Digital Health Insights — Latest Research from AI Experts",
    author: "@user",
    initials: "HT",
    views: "0 views",
    color: "#f6e3d6",
  },
];
